#!/usr/bin/env python3
"""Apply approved self-evolution decisions in a constrained local mode.

Default is dry-run. This script intentionally supports only a tiny safe subset:
append Markdown content to files under the development skill directory. It does
not write Hermes memory, call skill_manage, create cron jobs, or contact APIs.

To apply, a decision must have:
  status: approved
  apply.mode: append_markdown
  apply.path: relative path under references/, templates/, reports/, or SKILL.md
  apply.content: non-empty markdown text

Run with --apply to perform writes. Without --apply it only prints the plan.
"""
from __future__ import annotations

import argparse
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except Exception as exc:  # pragma: no cover
    raise SystemExit(f"PyYAML is required: {exc}")

ROOT = Path(__file__).resolve().parents[1]
ALLOWED_TOP_LEVEL = {"SKILL.md", "references", "templates", "reports"}
SECRET_PATTERNS = [
    re.compile(r"(?i)(api[_-]?key|authorization|token|password|secret)\s*[:=]\s*\S+"),
    re.compile(r"Bearer\s+[A-Za-z0-9._~+/=-]{12,}"),
    re.compile(r"(?i)(ghp|github_pat|sk-[A-Za-z0-9])[A-Za-z0-9_\-]{16,}"),
]


def has_secret(text: str) -> bool:
    return any(pattern.search(text or "") for pattern in SECRET_PATTERNS)


def resolve_allowed(path_text: str) -> Path:
    if not path_text:
        raise ValueError("apply.path is required")
    rel = Path(path_text)
    if rel.is_absolute() or ".." in rel.parts:
        raise ValueError(f"path must be relative and stay under dev skill: {path_text}")
    if rel.parts[0] not in ALLOWED_TOP_LEVEL:
        raise ValueError(f"path top-level not allowed: {path_text}")
    target = (ROOT / rel).resolve()
    if not str(target).startswith(str(ROOT.resolve())):
        raise ValueError(f"resolved path escapes root: {path_text}")
    if target.suffix.lower() not in {".md", ".yaml", ".yml", ""}:
        raise ValueError(f"only markdown/yaml-like files can be appended: {path_text}")
    return target


def append_markdown(target: Path, content: str, decision_id: str, apply: bool) -> str:
    if not content.strip():
        raise ValueError("apply.content is empty")
    if has_secret(content):
        raise ValueError("apply.content appears to contain a secret; redact before applying")
    block = (
        "\n\n"
        f"<!-- self-evolving-skills decision={decision_id} applied_at={datetime.now(timezone.utc).isoformat()} -->\n"
        f"{content.rstrip()}\n"
    )
    if apply:
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("a", encoding="utf-8") as fh:
            fh.write(block)
    try:
        display_path = str(target.relative_to(ROOT))
    except ValueError:
        display_path = str(target)
    return f"append {len(block)} chars -> {display_path}"


def verify_append(target: Path, decision_id: str, content: str) -> dict[str, Any]:
    """Read back an appended decision block and verify marker/content exist."""
    if not target.exists():
        return {"ok": False, "target": str(target), "reason": "target_missing"}
    text = target.read_text(encoding="utf-8")
    marker = f"self-evolving-skills decision={decision_id}"
    missing: list[str] = []
    if marker not in text:
        missing.append("decision_marker")
    if content.strip() and content.strip() not in text:
        missing.append("content")
    return {
        "ok": not missing,
        "target": str(target),
        "reason": "ok" if not missing else "missing:" + ",".join(missing),
    }


def load(path: Path) -> dict[str, Any]:
    doc = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict) or not isinstance(doc.get("decisions"), list):
        raise SystemExit("Decision file must contain a decisions list")
    return doc


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply approved self-evolution decisions in constrained mode.")
    parser.add_argument("decisions", type=Path, help="YAML generated by generate_decisions.py and reviewed by a human/agent")
    parser.add_argument("--apply", action="store_true", help="Actually write approved append_markdown changes")
    args = parser.parse_args()

    doc = load(args.decisions)
    planned: list[str] = []
    skipped: list[str] = []
    errors: list[str] = []

    for decision in doc.get("decisions", []):
        decision_id = str(decision.get("id", "unknown"))
        status = decision.get("status")
        apply_spec = decision.get("apply") or {}
        mode = apply_spec.get("mode", "manual")
        if status != "approved":
            skipped.append(f"{decision_id}: status={status}")
            continue
        if mode == "manual":
            skipped.append(f"{decision_id}: manual mode")
            continue
        if mode != "append_markdown":
            errors.append(f"{decision_id}: unsupported apply.mode={mode}")
            continue
        try:
            target = resolve_allowed(str(apply_spec.get("path", "")))
            content = str(apply_spec.get("content", ""))
            planned.append(f"{decision_id}: " + append_markdown(target, content, decision_id, args.apply))
            if args.apply:
                verification = verify_append(target, decision_id, content)
                planned.append(f"{decision_id}: verify_append={verification['ok']} reason={verification['reason']}")
        except Exception as exc:
            errors.append(f"{decision_id}: {exc}")

    print("MODE", "APPLY" if args.apply else "DRY_RUN")
    print("PLANNED")
    for item in planned:
        print("-", item)
    print("SKIPPED")
    for item in skipped[:50]:
        print("-", item)
    if len(skipped) > 50:
        print(f"- ... {len(skipped) - 50} more")
    if errors:
        print("ERRORS")
        for item in errors:
            print("-", item)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
